const actionTypes = {
  ADD: 'ADD',
  TICK: 'TICK',
  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOG_OUT: 'LOG_OUT',
  SAVE_TODO: 'SAVE_TODO',
  LOAD_JOKES_SUCCESS: 'LOAD_JOKES_SUCCESS',
  GET_PROFILE: 'GET_PROFILE',
  REFRESH_USER: 'REFRESH_USER',

  // current actions
  LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',

  // STORE
  SAVE_STORE: 'SAVE_STORE',
  LOAD_STORE_DATA: 'LOAD_STORE_DATA',
  RESET_STORE_DATA: 'RESET_STORE_DATA',
  LOAD_STORES_SUCCESS: 'LOAD_STORES_SUCCESS'
}

export default actionTypes
